version: 2.1

jobs:
  build:
    docker:
      - image: ryokik/circleci-wasm-pack:0.8.1
    working_directory: ~/bibi-zip-loader
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  release:
    docker:
      - image: ryokik/circleci-wasm-pack:0.8.1
    working_directory: ~/bibi-zip-loader
    steps:
      - checkout
      - run: npm install
      - run: npm pack
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/bibi-zip-loader/.npmrc
      - run: git config --global user.email "lunascape+circleci@users.noreply.github.com"
      - run: git config --global user.name "circleci"
      - run: npx release-it $(node -pe "require('./package.json').version")

workflows:
  build:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: /^release.*/
